baseURL: "https://kosalnith.github.io/" 
title: Kosal Nith
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /research/
          weight: 1
        - name: Teaching
          url: /teaching/
          weight: 2
        - name: Design
          url: /design/
          weight: 3
        - name: Tags
          url: /tags/
          weight: 5     
        - name: Newsletter
          url: https://econlab.substack.com
          weight: 4
        - name: Personal
          url: /personal/
          weight: 6
        - name: Speeches
          url: /speeches/
          weight: 7
        - name: Miscellaneous
          url: /miscellaneous/
          weight: 8
        - name: Search
          url: /search/
          weight: 9
params:
    description: "I am a Data Support Officer at Cambodia Development Resource Institute. My research covers unemployment, economic slack, business cycles, and macroeconomic policy."
    author: Kosal Nith
    googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Kosal Nith
          subtitle: "I am a Data Support Officer at Cambodia Development Resource Institute. I try to understand why economic slack—especially unemployment—exists and why it fluctuates over the business cycle. I also study how macroeconomic policies—including monetary policy, government spending, unemployment insurance, and immigration—should respond to such cyclical fluctuations."
          imageUrl: "/img/kosal.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Kosal Nith
          buttons:
            - name: Research
              url: /research/
            - name: Teaching
              url: /teaching/
            - name: Design
              url: /design/
            - name: Newsletter
              url: https://econlab.substack.com
            - name: Personal
              url: /personal/
            - name: Speeches
              url: /speeches/
            - name: Miscellaneous
              url: /miscellaneous/
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:kosal.nith@cdri.org.kh
        - name: Location
          url: /location/
        - name: Office Hours
          url: /officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=LG2mrO4AAAAJ&hl=en
        - name: YouTube
          url: https://www.youtube.com/@kosalnith
        - name: GitHub
          url: https://github.com/kosalnith

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Kosal Nith"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
